// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MatchingBattle.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MatchingBattle.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ReqMatchingBattle_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReqMatchingBattle_reflection_ = NULL;
const ::google::protobuf::Descriptor* RspMathingBattle_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RspMathingBattle_reflection_ = NULL;
const ::google::protobuf::Descriptor* EnterSelectHeroRoom_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  EnterSelectHeroRoom_reflection_ = NULL;
const ::google::protobuf::Descriptor* ReqSelectHero_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReqSelectHero_reflection_ = NULL;
const ::google::protobuf::Descriptor* RspSelectHero_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RspSelectHero_reflection_ = NULL;
const ::google::protobuf::Descriptor* UpdateRoomEnemyHero_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UpdateRoomEnemyHero_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoadBattleSceneBegin_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoadBattleSceneBegin_reflection_ = NULL;
const ::google::protobuf::Descriptor* ReqLoadBattleSceneEnd_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReqLoadBattleSceneEnd_reflection_ = NULL;
const ::google::protobuf::Descriptor* RspLoadBattleSceneEnd_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RspLoadBattleSceneEnd_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MatchingBattle_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_MatchingBattle_2eproto() {
  protobuf_AddDesc_MatchingBattle_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MatchingBattle.proto");
  GOOGLE_CHECK(file != NULL);
  ReqMatchingBattle_descriptor_ = file->message_type(0);
  static const int ReqMatchingBattle_offsets_[1] = {
  };
  ReqMatchingBattle_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReqMatchingBattle_descriptor_,
      ReqMatchingBattle::default_instance_,
      ReqMatchingBattle_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReqMatchingBattle),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqMatchingBattle, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqMatchingBattle, _is_default_instance_));
  RspMathingBattle_descriptor_ = file->message_type(1);
  static const int RspMathingBattle_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspMathingBattle, status_),
  };
  RspMathingBattle_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RspMathingBattle_descriptor_,
      RspMathingBattle::default_instance_,
      RspMathingBattle_offsets_,
      -1,
      -1,
      -1,
      sizeof(RspMathingBattle),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspMathingBattle, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspMathingBattle, _is_default_instance_));
  EnterSelectHeroRoom_descriptor_ = file->message_type(2);
  static const int EnterSelectHeroRoom_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EnterSelectHeroRoom, enemy_user_data_),
  };
  EnterSelectHeroRoom_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      EnterSelectHeroRoom_descriptor_,
      EnterSelectHeroRoom::default_instance_,
      EnterSelectHeroRoom_offsets_,
      -1,
      -1,
      -1,
      sizeof(EnterSelectHeroRoom),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EnterSelectHeroRoom, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EnterSelectHeroRoom, _is_default_instance_));
  ReqSelectHero_descriptor_ = file->message_type(3);
  static const int ReqSelectHero_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqSelectHero, hero_id_),
  };
  ReqSelectHero_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReqSelectHero_descriptor_,
      ReqSelectHero::default_instance_,
      ReqSelectHero_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReqSelectHero),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqSelectHero, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqSelectHero, _is_default_instance_));
  RspSelectHero_descriptor_ = file->message_type(4);
  static const int RspSelectHero_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspSelectHero, status_),
  };
  RspSelectHero_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RspSelectHero_descriptor_,
      RspSelectHero::default_instance_,
      RspSelectHero_offsets_,
      -1,
      -1,
      -1,
      sizeof(RspSelectHero),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspSelectHero, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspSelectHero, _is_default_instance_));
  UpdateRoomEnemyHero_descriptor_ = file->message_type(5);
  static const int UpdateRoomEnemyHero_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRoomEnemyHero, hero_id_),
  };
  UpdateRoomEnemyHero_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      UpdateRoomEnemyHero_descriptor_,
      UpdateRoomEnemyHero::default_instance_,
      UpdateRoomEnemyHero_offsets_,
      -1,
      -1,
      -1,
      sizeof(UpdateRoomEnemyHero),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRoomEnemyHero, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdateRoomEnemyHero, _is_default_instance_));
  LoadBattleSceneBegin_descriptor_ = file->message_type(6);
  static const int LoadBattleSceneBegin_offsets_[1] = {
  };
  LoadBattleSceneBegin_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LoadBattleSceneBegin_descriptor_,
      LoadBattleSceneBegin::default_instance_,
      LoadBattleSceneBegin_offsets_,
      -1,
      -1,
      -1,
      sizeof(LoadBattleSceneBegin),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadBattleSceneBegin, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadBattleSceneBegin, _is_default_instance_));
  ReqLoadBattleSceneEnd_descriptor_ = file->message_type(7);
  static const int ReqLoadBattleSceneEnd_offsets_[1] = {
  };
  ReqLoadBattleSceneEnd_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReqLoadBattleSceneEnd_descriptor_,
      ReqLoadBattleSceneEnd::default_instance_,
      ReqLoadBattleSceneEnd_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReqLoadBattleSceneEnd),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqLoadBattleSceneEnd, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReqLoadBattleSceneEnd, _is_default_instance_));
  RspLoadBattleSceneEnd_descriptor_ = file->message_type(8);
  static const int RspLoadBattleSceneEnd_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspLoadBattleSceneEnd, status_),
  };
  RspLoadBattleSceneEnd_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RspLoadBattleSceneEnd_descriptor_,
      RspLoadBattleSceneEnd::default_instance_,
      RspLoadBattleSceneEnd_offsets_,
      -1,
      -1,
      -1,
      sizeof(RspLoadBattleSceneEnd),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspLoadBattleSceneEnd, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RspLoadBattleSceneEnd, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MatchingBattle_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReqMatchingBattle_descriptor_, &ReqMatchingBattle::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RspMathingBattle_descriptor_, &RspMathingBattle::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      EnterSelectHeroRoom_descriptor_, &EnterSelectHeroRoom::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReqSelectHero_descriptor_, &ReqSelectHero::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RspSelectHero_descriptor_, &RspSelectHero::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      UpdateRoomEnemyHero_descriptor_, &UpdateRoomEnemyHero::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LoadBattleSceneBegin_descriptor_, &LoadBattleSceneBegin::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReqLoadBattleSceneEnd_descriptor_, &ReqLoadBattleSceneEnd::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RspLoadBattleSceneEnd_descriptor_, &RspLoadBattleSceneEnd::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MatchingBattle_2eproto() {
  delete ReqMatchingBattle::default_instance_;
  delete ReqMatchingBattle_reflection_;
  delete RspMathingBattle::default_instance_;
  delete RspMathingBattle_reflection_;
  delete EnterSelectHeroRoom::default_instance_;
  delete EnterSelectHeroRoom_reflection_;
  delete ReqSelectHero::default_instance_;
  delete ReqSelectHero_reflection_;
  delete RspSelectHero::default_instance_;
  delete RspSelectHero_reflection_;
  delete UpdateRoomEnemyHero::default_instance_;
  delete UpdateRoomEnemyHero_reflection_;
  delete LoadBattleSceneBegin::default_instance_;
  delete LoadBattleSceneBegin_reflection_;
  delete ReqLoadBattleSceneEnd::default_instance_;
  delete ReqLoadBattleSceneEnd_reflection_;
  delete RspLoadBattleSceneEnd::default_instance_;
  delete RspLoadBattleSceneEnd_reflection_;
}

void protobuf_AddDesc_MatchingBattle_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_MatchingBattle_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_UserData_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024MatchingBattle.proto\032\016UserData.proto\"\023"
    "\n\021ReqMatchingBattle\"\"\n\020RspMathingBattle\022"
    "\016\n\006status\030\001 \001(\010\"9\n\023EnterSelectHeroRoom\022\""
    "\n\017enemy_user_data\030\001 \001(\0132\t.UserData\" \n\rRe"
    "qSelectHero\022\017\n\007hero_id\030\001 \001(\005\"\037\n\rRspSelec"
    "tHero\022\016\n\006status\030\001 \001(\010\"&\n\023UpdateRoomEnemy"
    "Hero\022\017\n\007hero_id\030\001 \001(\005\"\026\n\024LoadBattleScene"
    "Begin\"\027\n\025ReqLoadBattleSceneEnd\"\'\n\025RspLoa"
    "dBattleSceneEnd\022\016\n\006status\030\001 \001(\010b\006proto3", 359);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MatchingBattle.proto", &protobuf_RegisterTypes);
  ReqMatchingBattle::default_instance_ = new ReqMatchingBattle();
  RspMathingBattle::default_instance_ = new RspMathingBattle();
  EnterSelectHeroRoom::default_instance_ = new EnterSelectHeroRoom();
  ReqSelectHero::default_instance_ = new ReqSelectHero();
  RspSelectHero::default_instance_ = new RspSelectHero();
  UpdateRoomEnemyHero::default_instance_ = new UpdateRoomEnemyHero();
  LoadBattleSceneBegin::default_instance_ = new LoadBattleSceneBegin();
  ReqLoadBattleSceneEnd::default_instance_ = new ReqLoadBattleSceneEnd();
  RspLoadBattleSceneEnd::default_instance_ = new RspLoadBattleSceneEnd();
  ReqMatchingBattle::default_instance_->InitAsDefaultInstance();
  RspMathingBattle::default_instance_->InitAsDefaultInstance();
  EnterSelectHeroRoom::default_instance_->InitAsDefaultInstance();
  ReqSelectHero::default_instance_->InitAsDefaultInstance();
  RspSelectHero::default_instance_->InitAsDefaultInstance();
  UpdateRoomEnemyHero::default_instance_->InitAsDefaultInstance();
  LoadBattleSceneBegin::default_instance_->InitAsDefaultInstance();
  ReqLoadBattleSceneEnd::default_instance_->InitAsDefaultInstance();
  RspLoadBattleSceneEnd::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MatchingBattle_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MatchingBattle_2eproto {
  StaticDescriptorInitializer_MatchingBattle_2eproto() {
    protobuf_AddDesc_MatchingBattle_2eproto();
  }
} static_descriptor_initializer_MatchingBattle_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqMatchingBattle::ReqMatchingBattle()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ReqMatchingBattle)
}

void ReqMatchingBattle::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ReqMatchingBattle::ReqMatchingBattle(const ReqMatchingBattle& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ReqMatchingBattle)
}

void ReqMatchingBattle::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ReqMatchingBattle::~ReqMatchingBattle() {
  // @@protoc_insertion_point(destructor:ReqMatchingBattle)
  SharedDtor();
}

void ReqMatchingBattle::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReqMatchingBattle::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReqMatchingBattle::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReqMatchingBattle_descriptor_;
}

const ReqMatchingBattle& ReqMatchingBattle::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

ReqMatchingBattle* ReqMatchingBattle::default_instance_ = NULL;

ReqMatchingBattle* ReqMatchingBattle::New(::google::protobuf::Arena* arena) const {
  ReqMatchingBattle* n = new ReqMatchingBattle;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReqMatchingBattle::Clear() {
// @@protoc_insertion_point(message_clear_start:ReqMatchingBattle)
}

bool ReqMatchingBattle::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ReqMatchingBattle)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:ReqMatchingBattle)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ReqMatchingBattle)
  return false;
#undef DO_
}

void ReqMatchingBattle::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ReqMatchingBattle)
  // @@protoc_insertion_point(serialize_end:ReqMatchingBattle)
}

::google::protobuf::uint8* ReqMatchingBattle::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ReqMatchingBattle)
  // @@protoc_insertion_point(serialize_to_array_end:ReqMatchingBattle)
  return target;
}

int ReqMatchingBattle::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ReqMatchingBattle)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReqMatchingBattle::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ReqMatchingBattle)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ReqMatchingBattle* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqMatchingBattle>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ReqMatchingBattle)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ReqMatchingBattle)
    MergeFrom(*source);
  }
}

void ReqMatchingBattle::MergeFrom(const ReqMatchingBattle& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ReqMatchingBattle)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void ReqMatchingBattle::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ReqMatchingBattle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqMatchingBattle::CopyFrom(const ReqMatchingBattle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReqMatchingBattle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqMatchingBattle::IsInitialized() const {

  return true;
}

void ReqMatchingBattle::Swap(ReqMatchingBattle* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqMatchingBattle::InternalSwap(ReqMatchingBattle* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReqMatchingBattle::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReqMatchingBattle_descriptor_;
  metadata.reflection = ReqMatchingBattle_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReqMatchingBattle

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RspMathingBattle::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RspMathingBattle::RspMathingBattle()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RspMathingBattle)
}

void RspMathingBattle::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

RspMathingBattle::RspMathingBattle(const RspMathingBattle& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:RspMathingBattle)
}

void RspMathingBattle::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  status_ = false;
}

RspMathingBattle::~RspMathingBattle() {
  // @@protoc_insertion_point(destructor:RspMathingBattle)
  SharedDtor();
}

void RspMathingBattle::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RspMathingBattle::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RspMathingBattle::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RspMathingBattle_descriptor_;
}

const RspMathingBattle& RspMathingBattle::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

RspMathingBattle* RspMathingBattle::default_instance_ = NULL;

RspMathingBattle* RspMathingBattle::New(::google::protobuf::Arena* arena) const {
  RspMathingBattle* n = new RspMathingBattle;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RspMathingBattle::Clear() {
// @@protoc_insertion_point(message_clear_start:RspMathingBattle)
  status_ = false;
}

bool RspMathingBattle::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RspMathingBattle)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool status = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &status_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RspMathingBattle)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RspMathingBattle)
  return false;
#undef DO_
}

void RspMathingBattle::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RspMathingBattle)
  // optional bool status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->status(), output);
  }

  // @@protoc_insertion_point(serialize_end:RspMathingBattle)
}

::google::protobuf::uint8* RspMathingBattle::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RspMathingBattle)
  // optional bool status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->status(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:RspMathingBattle)
  return target;
}

int RspMathingBattle::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:RspMathingBattle)
  int total_size = 0;

  // optional bool status = 1;
  if (this->status() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RspMathingBattle::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RspMathingBattle)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RspMathingBattle* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RspMathingBattle>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RspMathingBattle)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RspMathingBattle)
    MergeFrom(*source);
  }
}

void RspMathingBattle::MergeFrom(const RspMathingBattle& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RspMathingBattle)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void RspMathingBattle::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RspMathingBattle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RspMathingBattle::CopyFrom(const RspMathingBattle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RspMathingBattle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RspMathingBattle::IsInitialized() const {

  return true;
}

void RspMathingBattle::Swap(RspMathingBattle* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RspMathingBattle::InternalSwap(RspMathingBattle* other) {
  std::swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RspMathingBattle::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RspMathingBattle_descriptor_;
  metadata.reflection = RspMathingBattle_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RspMathingBattle

// optional bool status = 1;
void RspMathingBattle::clear_status() {
  status_ = false;
}
 bool RspMathingBattle::status() const {
  // @@protoc_insertion_point(field_get:RspMathingBattle.status)
  return status_;
}
 void RspMathingBattle::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:RspMathingBattle.status)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EnterSelectHeroRoom::kEnemyUserDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EnterSelectHeroRoom::EnterSelectHeroRoom()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:EnterSelectHeroRoom)
}

void EnterSelectHeroRoom::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  enemy_user_data_ = const_cast< ::UserData*>(&::UserData::default_instance());
}

EnterSelectHeroRoom::EnterSelectHeroRoom(const EnterSelectHeroRoom& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:EnterSelectHeroRoom)
}

void EnterSelectHeroRoom::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  enemy_user_data_ = NULL;
}

EnterSelectHeroRoom::~EnterSelectHeroRoom() {
  // @@protoc_insertion_point(destructor:EnterSelectHeroRoom)
  SharedDtor();
}

void EnterSelectHeroRoom::SharedDtor() {
  if (this != default_instance_) {
    delete enemy_user_data_;
  }
}

void EnterSelectHeroRoom::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EnterSelectHeroRoom::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EnterSelectHeroRoom_descriptor_;
}

const EnterSelectHeroRoom& EnterSelectHeroRoom::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

EnterSelectHeroRoom* EnterSelectHeroRoom::default_instance_ = NULL;

EnterSelectHeroRoom* EnterSelectHeroRoom::New(::google::protobuf::Arena* arena) const {
  EnterSelectHeroRoom* n = new EnterSelectHeroRoom;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EnterSelectHeroRoom::Clear() {
// @@protoc_insertion_point(message_clear_start:EnterSelectHeroRoom)
  if (GetArenaNoVirtual() == NULL && enemy_user_data_ != NULL) delete enemy_user_data_;
  enemy_user_data_ = NULL;
}

bool EnterSelectHeroRoom::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EnterSelectHeroRoom)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .UserData enemy_user_data = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_enemy_user_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EnterSelectHeroRoom)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EnterSelectHeroRoom)
  return false;
#undef DO_
}

void EnterSelectHeroRoom::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EnterSelectHeroRoom)
  // optional .UserData enemy_user_data = 1;
  if (this->has_enemy_user_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->enemy_user_data_, output);
  }

  // @@protoc_insertion_point(serialize_end:EnterSelectHeroRoom)
}

::google::protobuf::uint8* EnterSelectHeroRoom::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:EnterSelectHeroRoom)
  // optional .UserData enemy_user_data = 1;
  if (this->has_enemy_user_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->enemy_user_data_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:EnterSelectHeroRoom)
  return target;
}

int EnterSelectHeroRoom::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:EnterSelectHeroRoom)
  int total_size = 0;

  // optional .UserData enemy_user_data = 1;
  if (this->has_enemy_user_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->enemy_user_data_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EnterSelectHeroRoom::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EnterSelectHeroRoom)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const EnterSelectHeroRoom* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const EnterSelectHeroRoom>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EnterSelectHeroRoom)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EnterSelectHeroRoom)
    MergeFrom(*source);
  }
}

void EnterSelectHeroRoom::MergeFrom(const EnterSelectHeroRoom& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EnterSelectHeroRoom)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_enemy_user_data()) {
    mutable_enemy_user_data()->::UserData::MergeFrom(from.enemy_user_data());
  }
}

void EnterSelectHeroRoom::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EnterSelectHeroRoom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EnterSelectHeroRoom::CopyFrom(const EnterSelectHeroRoom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EnterSelectHeroRoom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnterSelectHeroRoom::IsInitialized() const {

  return true;
}

void EnterSelectHeroRoom::Swap(EnterSelectHeroRoom* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EnterSelectHeroRoom::InternalSwap(EnterSelectHeroRoom* other) {
  std::swap(enemy_user_data_, other->enemy_user_data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EnterSelectHeroRoom::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = EnterSelectHeroRoom_descriptor_;
  metadata.reflection = EnterSelectHeroRoom_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EnterSelectHeroRoom

// optional .UserData enemy_user_data = 1;
bool EnterSelectHeroRoom::has_enemy_user_data() const {
  return !_is_default_instance_ && enemy_user_data_ != NULL;
}
void EnterSelectHeroRoom::clear_enemy_user_data() {
  if (GetArenaNoVirtual() == NULL && enemy_user_data_ != NULL) delete enemy_user_data_;
  enemy_user_data_ = NULL;
}
const ::UserData& EnterSelectHeroRoom::enemy_user_data() const {
  // @@protoc_insertion_point(field_get:EnterSelectHeroRoom.enemy_user_data)
  return enemy_user_data_ != NULL ? *enemy_user_data_ : *default_instance_->enemy_user_data_;
}
::UserData* EnterSelectHeroRoom::mutable_enemy_user_data() {
  
  if (enemy_user_data_ == NULL) {
    enemy_user_data_ = new ::UserData;
  }
  // @@protoc_insertion_point(field_mutable:EnterSelectHeroRoom.enemy_user_data)
  return enemy_user_data_;
}
::UserData* EnterSelectHeroRoom::release_enemy_user_data() {
  // @@protoc_insertion_point(field_release:EnterSelectHeroRoom.enemy_user_data)
  
  ::UserData* temp = enemy_user_data_;
  enemy_user_data_ = NULL;
  return temp;
}
void EnterSelectHeroRoom::set_allocated_enemy_user_data(::UserData* enemy_user_data) {
  delete enemy_user_data_;
  enemy_user_data_ = enemy_user_data;
  if (enemy_user_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:EnterSelectHeroRoom.enemy_user_data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReqSelectHero::kHeroIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqSelectHero::ReqSelectHero()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ReqSelectHero)
}

void ReqSelectHero::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ReqSelectHero::ReqSelectHero(const ReqSelectHero& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ReqSelectHero)
}

void ReqSelectHero::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  hero_id_ = 0;
}

ReqSelectHero::~ReqSelectHero() {
  // @@protoc_insertion_point(destructor:ReqSelectHero)
  SharedDtor();
}

void ReqSelectHero::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReqSelectHero::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReqSelectHero::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReqSelectHero_descriptor_;
}

const ReqSelectHero& ReqSelectHero::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

ReqSelectHero* ReqSelectHero::default_instance_ = NULL;

ReqSelectHero* ReqSelectHero::New(::google::protobuf::Arena* arena) const {
  ReqSelectHero* n = new ReqSelectHero;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReqSelectHero::Clear() {
// @@protoc_insertion_point(message_clear_start:ReqSelectHero)
  hero_id_ = 0;
}

bool ReqSelectHero::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ReqSelectHero)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 hero_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hero_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ReqSelectHero)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ReqSelectHero)
  return false;
#undef DO_
}

void ReqSelectHero::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ReqSelectHero)
  // optional int32 hero_id = 1;
  if (this->hero_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->hero_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:ReqSelectHero)
}

::google::protobuf::uint8* ReqSelectHero::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ReqSelectHero)
  // optional int32 hero_id = 1;
  if (this->hero_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->hero_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ReqSelectHero)
  return target;
}

int ReqSelectHero::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ReqSelectHero)
  int total_size = 0;

  // optional int32 hero_id = 1;
  if (this->hero_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->hero_id());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReqSelectHero::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ReqSelectHero)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ReqSelectHero* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqSelectHero>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ReqSelectHero)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ReqSelectHero)
    MergeFrom(*source);
  }
}

void ReqSelectHero::MergeFrom(const ReqSelectHero& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ReqSelectHero)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.hero_id() != 0) {
    set_hero_id(from.hero_id());
  }
}

void ReqSelectHero::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ReqSelectHero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqSelectHero::CopyFrom(const ReqSelectHero& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReqSelectHero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqSelectHero::IsInitialized() const {

  return true;
}

void ReqSelectHero::Swap(ReqSelectHero* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqSelectHero::InternalSwap(ReqSelectHero* other) {
  std::swap(hero_id_, other->hero_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReqSelectHero::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReqSelectHero_descriptor_;
  metadata.reflection = ReqSelectHero_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReqSelectHero

// optional int32 hero_id = 1;
void ReqSelectHero::clear_hero_id() {
  hero_id_ = 0;
}
 ::google::protobuf::int32 ReqSelectHero::hero_id() const {
  // @@protoc_insertion_point(field_get:ReqSelectHero.hero_id)
  return hero_id_;
}
 void ReqSelectHero::set_hero_id(::google::protobuf::int32 value) {
  
  hero_id_ = value;
  // @@protoc_insertion_point(field_set:ReqSelectHero.hero_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RspSelectHero::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RspSelectHero::RspSelectHero()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RspSelectHero)
}

void RspSelectHero::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

RspSelectHero::RspSelectHero(const RspSelectHero& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:RspSelectHero)
}

void RspSelectHero::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  status_ = false;
}

RspSelectHero::~RspSelectHero() {
  // @@protoc_insertion_point(destructor:RspSelectHero)
  SharedDtor();
}

void RspSelectHero::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RspSelectHero::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RspSelectHero::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RspSelectHero_descriptor_;
}

const RspSelectHero& RspSelectHero::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

RspSelectHero* RspSelectHero::default_instance_ = NULL;

RspSelectHero* RspSelectHero::New(::google::protobuf::Arena* arena) const {
  RspSelectHero* n = new RspSelectHero;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RspSelectHero::Clear() {
// @@protoc_insertion_point(message_clear_start:RspSelectHero)
  status_ = false;
}

bool RspSelectHero::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RspSelectHero)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool status = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &status_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RspSelectHero)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RspSelectHero)
  return false;
#undef DO_
}

void RspSelectHero::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RspSelectHero)
  // optional bool status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->status(), output);
  }

  // @@protoc_insertion_point(serialize_end:RspSelectHero)
}

::google::protobuf::uint8* RspSelectHero::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RspSelectHero)
  // optional bool status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->status(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:RspSelectHero)
  return target;
}

int RspSelectHero::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:RspSelectHero)
  int total_size = 0;

  // optional bool status = 1;
  if (this->status() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RspSelectHero::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RspSelectHero)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RspSelectHero* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RspSelectHero>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RspSelectHero)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RspSelectHero)
    MergeFrom(*source);
  }
}

void RspSelectHero::MergeFrom(const RspSelectHero& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RspSelectHero)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void RspSelectHero::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RspSelectHero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RspSelectHero::CopyFrom(const RspSelectHero& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RspSelectHero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RspSelectHero::IsInitialized() const {

  return true;
}

void RspSelectHero::Swap(RspSelectHero* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RspSelectHero::InternalSwap(RspSelectHero* other) {
  std::swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RspSelectHero::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RspSelectHero_descriptor_;
  metadata.reflection = RspSelectHero_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RspSelectHero

// optional bool status = 1;
void RspSelectHero::clear_status() {
  status_ = false;
}
 bool RspSelectHero::status() const {
  // @@protoc_insertion_point(field_get:RspSelectHero.status)
  return status_;
}
 void RspSelectHero::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:RspSelectHero.status)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UpdateRoomEnemyHero::kHeroIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UpdateRoomEnemyHero::UpdateRoomEnemyHero()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:UpdateRoomEnemyHero)
}

void UpdateRoomEnemyHero::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

UpdateRoomEnemyHero::UpdateRoomEnemyHero(const UpdateRoomEnemyHero& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:UpdateRoomEnemyHero)
}

void UpdateRoomEnemyHero::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  hero_id_ = 0;
}

UpdateRoomEnemyHero::~UpdateRoomEnemyHero() {
  // @@protoc_insertion_point(destructor:UpdateRoomEnemyHero)
  SharedDtor();
}

void UpdateRoomEnemyHero::SharedDtor() {
  if (this != default_instance_) {
  }
}

void UpdateRoomEnemyHero::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UpdateRoomEnemyHero::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UpdateRoomEnemyHero_descriptor_;
}

const UpdateRoomEnemyHero& UpdateRoomEnemyHero::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

UpdateRoomEnemyHero* UpdateRoomEnemyHero::default_instance_ = NULL;

UpdateRoomEnemyHero* UpdateRoomEnemyHero::New(::google::protobuf::Arena* arena) const {
  UpdateRoomEnemyHero* n = new UpdateRoomEnemyHero;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UpdateRoomEnemyHero::Clear() {
// @@protoc_insertion_point(message_clear_start:UpdateRoomEnemyHero)
  hero_id_ = 0;
}

bool UpdateRoomEnemyHero::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:UpdateRoomEnemyHero)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 hero_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hero_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:UpdateRoomEnemyHero)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:UpdateRoomEnemyHero)
  return false;
#undef DO_
}

void UpdateRoomEnemyHero::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:UpdateRoomEnemyHero)
  // optional int32 hero_id = 1;
  if (this->hero_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->hero_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:UpdateRoomEnemyHero)
}

::google::protobuf::uint8* UpdateRoomEnemyHero::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:UpdateRoomEnemyHero)
  // optional int32 hero_id = 1;
  if (this->hero_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->hero_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:UpdateRoomEnemyHero)
  return target;
}

int UpdateRoomEnemyHero::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:UpdateRoomEnemyHero)
  int total_size = 0;

  // optional int32 hero_id = 1;
  if (this->hero_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->hero_id());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UpdateRoomEnemyHero::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:UpdateRoomEnemyHero)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const UpdateRoomEnemyHero* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const UpdateRoomEnemyHero>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:UpdateRoomEnemyHero)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:UpdateRoomEnemyHero)
    MergeFrom(*source);
  }
}

void UpdateRoomEnemyHero::MergeFrom(const UpdateRoomEnemyHero& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:UpdateRoomEnemyHero)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.hero_id() != 0) {
    set_hero_id(from.hero_id());
  }
}

void UpdateRoomEnemyHero::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:UpdateRoomEnemyHero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdateRoomEnemyHero::CopyFrom(const UpdateRoomEnemyHero& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UpdateRoomEnemyHero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdateRoomEnemyHero::IsInitialized() const {

  return true;
}

void UpdateRoomEnemyHero::Swap(UpdateRoomEnemyHero* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UpdateRoomEnemyHero::InternalSwap(UpdateRoomEnemyHero* other) {
  std::swap(hero_id_, other->hero_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UpdateRoomEnemyHero::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UpdateRoomEnemyHero_descriptor_;
  metadata.reflection = UpdateRoomEnemyHero_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UpdateRoomEnemyHero

// optional int32 hero_id = 1;
void UpdateRoomEnemyHero::clear_hero_id() {
  hero_id_ = 0;
}
 ::google::protobuf::int32 UpdateRoomEnemyHero::hero_id() const {
  // @@protoc_insertion_point(field_get:UpdateRoomEnemyHero.hero_id)
  return hero_id_;
}
 void UpdateRoomEnemyHero::set_hero_id(::google::protobuf::int32 value) {
  
  hero_id_ = value;
  // @@protoc_insertion_point(field_set:UpdateRoomEnemyHero.hero_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoadBattleSceneBegin::LoadBattleSceneBegin()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:LoadBattleSceneBegin)
}

void LoadBattleSceneBegin::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

LoadBattleSceneBegin::LoadBattleSceneBegin(const LoadBattleSceneBegin& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:LoadBattleSceneBegin)
}

void LoadBattleSceneBegin::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

LoadBattleSceneBegin::~LoadBattleSceneBegin() {
  // @@protoc_insertion_point(destructor:LoadBattleSceneBegin)
  SharedDtor();
}

void LoadBattleSceneBegin::SharedDtor() {
  if (this != default_instance_) {
  }
}

void LoadBattleSceneBegin::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoadBattleSceneBegin::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoadBattleSceneBegin_descriptor_;
}

const LoadBattleSceneBegin& LoadBattleSceneBegin::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

LoadBattleSceneBegin* LoadBattleSceneBegin::default_instance_ = NULL;

LoadBattleSceneBegin* LoadBattleSceneBegin::New(::google::protobuf::Arena* arena) const {
  LoadBattleSceneBegin* n = new LoadBattleSceneBegin;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoadBattleSceneBegin::Clear() {
// @@protoc_insertion_point(message_clear_start:LoadBattleSceneBegin)
}

bool LoadBattleSceneBegin::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LoadBattleSceneBegin)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:LoadBattleSceneBegin)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LoadBattleSceneBegin)
  return false;
#undef DO_
}

void LoadBattleSceneBegin::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LoadBattleSceneBegin)
  // @@protoc_insertion_point(serialize_end:LoadBattleSceneBegin)
}

::google::protobuf::uint8* LoadBattleSceneBegin::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:LoadBattleSceneBegin)
  // @@protoc_insertion_point(serialize_to_array_end:LoadBattleSceneBegin)
  return target;
}

int LoadBattleSceneBegin::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:LoadBattleSceneBegin)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoadBattleSceneBegin::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LoadBattleSceneBegin)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const LoadBattleSceneBegin* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LoadBattleSceneBegin>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LoadBattleSceneBegin)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LoadBattleSceneBegin)
    MergeFrom(*source);
  }
}

void LoadBattleSceneBegin::MergeFrom(const LoadBattleSceneBegin& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LoadBattleSceneBegin)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void LoadBattleSceneBegin::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LoadBattleSceneBegin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoadBattleSceneBegin::CopyFrom(const LoadBattleSceneBegin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoadBattleSceneBegin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoadBattleSceneBegin::IsInitialized() const {

  return true;
}

void LoadBattleSceneBegin::Swap(LoadBattleSceneBegin* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoadBattleSceneBegin::InternalSwap(LoadBattleSceneBegin* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoadBattleSceneBegin::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoadBattleSceneBegin_descriptor_;
  metadata.reflection = LoadBattleSceneBegin_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoadBattleSceneBegin

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReqLoadBattleSceneEnd::ReqLoadBattleSceneEnd()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ReqLoadBattleSceneEnd)
}

void ReqLoadBattleSceneEnd::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ReqLoadBattleSceneEnd::ReqLoadBattleSceneEnd(const ReqLoadBattleSceneEnd& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ReqLoadBattleSceneEnd)
}

void ReqLoadBattleSceneEnd::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ReqLoadBattleSceneEnd::~ReqLoadBattleSceneEnd() {
  // @@protoc_insertion_point(destructor:ReqLoadBattleSceneEnd)
  SharedDtor();
}

void ReqLoadBattleSceneEnd::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ReqLoadBattleSceneEnd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReqLoadBattleSceneEnd::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReqLoadBattleSceneEnd_descriptor_;
}

const ReqLoadBattleSceneEnd& ReqLoadBattleSceneEnd::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

ReqLoadBattleSceneEnd* ReqLoadBattleSceneEnd::default_instance_ = NULL;

ReqLoadBattleSceneEnd* ReqLoadBattleSceneEnd::New(::google::protobuf::Arena* arena) const {
  ReqLoadBattleSceneEnd* n = new ReqLoadBattleSceneEnd;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReqLoadBattleSceneEnd::Clear() {
// @@protoc_insertion_point(message_clear_start:ReqLoadBattleSceneEnd)
}

bool ReqLoadBattleSceneEnd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ReqLoadBattleSceneEnd)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:ReqLoadBattleSceneEnd)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ReqLoadBattleSceneEnd)
  return false;
#undef DO_
}

void ReqLoadBattleSceneEnd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ReqLoadBattleSceneEnd)
  // @@protoc_insertion_point(serialize_end:ReqLoadBattleSceneEnd)
}

::google::protobuf::uint8* ReqLoadBattleSceneEnd::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ReqLoadBattleSceneEnd)
  // @@protoc_insertion_point(serialize_to_array_end:ReqLoadBattleSceneEnd)
  return target;
}

int ReqLoadBattleSceneEnd::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ReqLoadBattleSceneEnd)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReqLoadBattleSceneEnd::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ReqLoadBattleSceneEnd)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ReqLoadBattleSceneEnd* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ReqLoadBattleSceneEnd>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ReqLoadBattleSceneEnd)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ReqLoadBattleSceneEnd)
    MergeFrom(*source);
  }
}

void ReqLoadBattleSceneEnd::MergeFrom(const ReqLoadBattleSceneEnd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ReqLoadBattleSceneEnd)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void ReqLoadBattleSceneEnd::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ReqLoadBattleSceneEnd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqLoadBattleSceneEnd::CopyFrom(const ReqLoadBattleSceneEnd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ReqLoadBattleSceneEnd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqLoadBattleSceneEnd::IsInitialized() const {

  return true;
}

void ReqLoadBattleSceneEnd::Swap(ReqLoadBattleSceneEnd* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReqLoadBattleSceneEnd::InternalSwap(ReqLoadBattleSceneEnd* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReqLoadBattleSceneEnd::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReqLoadBattleSceneEnd_descriptor_;
  metadata.reflection = ReqLoadBattleSceneEnd_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReqLoadBattleSceneEnd

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RspLoadBattleSceneEnd::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RspLoadBattleSceneEnd::RspLoadBattleSceneEnd()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:RspLoadBattleSceneEnd)
}

void RspLoadBattleSceneEnd::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

RspLoadBattleSceneEnd::RspLoadBattleSceneEnd(const RspLoadBattleSceneEnd& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:RspLoadBattleSceneEnd)
}

void RspLoadBattleSceneEnd::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  status_ = false;
}

RspLoadBattleSceneEnd::~RspLoadBattleSceneEnd() {
  // @@protoc_insertion_point(destructor:RspLoadBattleSceneEnd)
  SharedDtor();
}

void RspLoadBattleSceneEnd::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RspLoadBattleSceneEnd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RspLoadBattleSceneEnd::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RspLoadBattleSceneEnd_descriptor_;
}

const RspLoadBattleSceneEnd& RspLoadBattleSceneEnd::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MatchingBattle_2eproto();
  return *default_instance_;
}

RspLoadBattleSceneEnd* RspLoadBattleSceneEnd::default_instance_ = NULL;

RspLoadBattleSceneEnd* RspLoadBattleSceneEnd::New(::google::protobuf::Arena* arena) const {
  RspLoadBattleSceneEnd* n = new RspLoadBattleSceneEnd;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RspLoadBattleSceneEnd::Clear() {
// @@protoc_insertion_point(message_clear_start:RspLoadBattleSceneEnd)
  status_ = false;
}

bool RspLoadBattleSceneEnd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RspLoadBattleSceneEnd)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool status = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &status_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RspLoadBattleSceneEnd)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RspLoadBattleSceneEnd)
  return false;
#undef DO_
}

void RspLoadBattleSceneEnd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RspLoadBattleSceneEnd)
  // optional bool status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->status(), output);
  }

  // @@protoc_insertion_point(serialize_end:RspLoadBattleSceneEnd)
}

::google::protobuf::uint8* RspLoadBattleSceneEnd::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RspLoadBattleSceneEnd)
  // optional bool status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->status(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:RspLoadBattleSceneEnd)
  return target;
}

int RspLoadBattleSceneEnd::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:RspLoadBattleSceneEnd)
  int total_size = 0;

  // optional bool status = 1;
  if (this->status() != 0) {
    total_size += 1 + 1;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RspLoadBattleSceneEnd::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RspLoadBattleSceneEnd)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const RspLoadBattleSceneEnd* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const RspLoadBattleSceneEnd>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RspLoadBattleSceneEnd)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RspLoadBattleSceneEnd)
    MergeFrom(*source);
  }
}

void RspLoadBattleSceneEnd::MergeFrom(const RspLoadBattleSceneEnd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RspLoadBattleSceneEnd)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void RspLoadBattleSceneEnd::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RspLoadBattleSceneEnd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RspLoadBattleSceneEnd::CopyFrom(const RspLoadBattleSceneEnd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RspLoadBattleSceneEnd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RspLoadBattleSceneEnd::IsInitialized() const {

  return true;
}

void RspLoadBattleSceneEnd::Swap(RspLoadBattleSceneEnd* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RspLoadBattleSceneEnd::InternalSwap(RspLoadBattleSceneEnd* other) {
  std::swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RspLoadBattleSceneEnd::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RspLoadBattleSceneEnd_descriptor_;
  metadata.reflection = RspLoadBattleSceneEnd_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RspLoadBattleSceneEnd

// optional bool status = 1;
void RspLoadBattleSceneEnd::clear_status() {
  status_ = false;
}
 bool RspLoadBattleSceneEnd::status() const {
  // @@protoc_insertion_point(field_get:RspLoadBattleSceneEnd.status)
  return status_;
}
 void RspLoadBattleSceneEnd::set_status(bool value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:RspLoadBattleSceneEnd.status)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
