//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/ReturnMessage.proto
namespace protos.ReturnMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResDefaultInfo")]
  public partial class ResDefaultInfo : global::ProtoBuf.IExtensible
  {
    public ResDefaultInfo() {}
    
    private int _results = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results
    {
      get { return _results; }
      set { _results = value; }
    }
    private string _details = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string details
    {
      get { return _details; }
      set { _details = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}